"""add pattern is_active

Revision ID: 956e43a33559
Revises: a1bae89e63e8
Create Date: 2026-05-28 11:02:04.124468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956e43a33559'
down_revision = 'a1bae89e63e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
