"""init

Revision ID: a1bae89e63e8
Revises: 
Create Date: 2026-05-28 00:15:51.634410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bae89e63e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_item_code', sa.String(length=128), nullable=False),
    sa.Column('child_item_code', sa.String(length=128), nullable=False),
    sa.Column('process_sequence', sa.JSON(), nullable=True),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('process_sequence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_code', sa.String(length=10), nullable=False),
    sa.Column('pattern_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_code')
    )
    op.create_table('sap_push_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_fg_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=128), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('thickness', sa.String(length=32), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('bom_template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bom_template_id'], ['bom_templates.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('generated_process_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fg_item_id', sa.Integer(), nullable=True),
    sa.Column('process_code', sa.String(length=32), nullable=False),
    sa.Column('item_code', sa.String(length=128), nullable=False),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fg_item_id'], ['generated_fg_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_process_items')
    op.drop_table('generated_fg_items')
    op.drop_table('sap_push_logs')
    op.drop_table('patterns')
    op.drop_table('material_types')
    op.drop_table('bom_templates')
    op.drop_table('bom_structures')
    # ### end Alembic commands ###
