"""add_unit2_manufacturing_job_tables

Revision ID: bb8141a0713b
Revises: b8c9d0e1f2a3
Create Date: 2026-06-03 11:21:25.383698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb8141a0713b'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def _drop_mrp_tables_if_present() -> None:
    """Unit 1 fresh DBs never had MRP tables; skip drops when absent."""
    bind = op.get_bind()
    tables = set(inspect(bind).get_table_names())
    if 'mrp_recommendations' in tables:
        for idx in ('ix_mrp_recommendations_run_id', 'ix_mrp_recommendations_status'):
            try:
                op.drop_index(op.f(idx), table_name='mrp_recommendations')
            except Exception:
                pass
        op.drop_table('mrp_recommendations')
    if 'mrp_runs' in tables:
        op.drop_table('mrp_runs')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_workcenter', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_master_category'), 'process_master', ['category'], unique=False)
    op.create_index(op.f('ix_process_master_process_code'), 'process_master', ['process_code'], unique=True)
    op.create_table('sap_customer_mirror',
    sa.Column('card_code', sa.String(length=30), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('card_code')
    )
    op.create_index(op.f('ix_sap_customer_mirror_synced_at'), 'sap_customer_mirror', ['synced_at'], unique=False)
    op.create_table('sap_item_mirror',
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('item_type', sa.Enum('fg', 'raw_material', 'consumable', 'service', name='sap_item_type'), nullable=True),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_code')
    )
    op.create_index(op.f('ix_sap_item_mirror_item_type'), 'sap_item_mirror', ['item_type'], unique=False)
    op.create_index(op.f('ix_sap_item_mirror_synced_at'), 'sap_item_mirror', ['synced_at'], unique=False)
    op.create_table('sap_mirror_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_full_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_customer_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_item_sync_at', sa.DateTime(), nullable=True),
    sa.Column('customer_row_count', sa.Integer(), nullable=True),
    sa.Column('item_row_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_number', sa.String(length=20), nullable=False),
    sa.Column('sap_customer_code', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority_type'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sap_production_order', sa.String(length=50), nullable=True),
    sa.Column('sap_bom_number', sa.String(length=50), nullable=True),
    sa.Column('sap_so_doc_num', sa.String(length=50), nullable=True),
    sa.Column('sap_so_doc_entry', sa.Integer(), nullable=True),
    sa.Column('sap_mjd1_line_code', sa.String(length=120), nullable=True),
    sa.Column('sap_fg_code', sa.String(length=100), nullable=True),
    sa.Column('sap_fg_name_snap', sa.String(length=200), nullable=True),
    sa.Column('sap_selected_lines_json', sa.Text(), nullable=True),
    sa.Column('process_sequence_json', sa.Text(), nullable=True),
    sa.Column('carton_length_mm', sa.Float(), nullable=True),
    sa.Column('carton_width_mm', sa.Float(), nullable=True),
    sa.Column('carton_height_mm', sa.Float(), nullable=True),
    sa.Column('job_kind', sa.String(length=20), nullable=True),
    sa.Column('sap_po_doc_entries_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sap_customer_code'], ['sap_customer_mirror.card_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_cards_job_card_number'), 'job_cards', ['job_card_number'], unique=True)
    op.create_table('job_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_no', sa.String(length=20), nullable=False),
    sa.Column('sap_customer_code', sa.String(length=20), nullable=True),
    sa.Column('sap_customer_name_snap', sa.String(length=200), nullable=True),
    sa.Column('sap_so_entry', sa.Integer(), nullable=True),
    sa.Column('sap_so_number_snap', sa.String(length=20), nullable=True),
    sa.Column('sap_job_card_doc_entry', sa.Integer(), nullable=True),
    sa.Column('sap_job_card_doc_num_snap', sa.String(length=30), nullable=True),
    sa.Column('sap_job_card_series_snap', sa.String(length=30), nullable=True),
    sa.Column('sap_job_card_title_snap', sa.String(length=200), nullable=True),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'urgent', name='job_priority'), nullable=False),
    sa.Column('job_type_cat', sa.String(length=20), nullable=True),
    sa.Column('job_series', sa.String(length=20), nullable=True),
    sa.Column('original_job_no', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('assigned_planner_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_planner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_master_job_no'), 'job_master', ['job_no'], unique=True)
    op.create_index(op.f('ix_job_master_original_job_no'), 'job_master', ['original_job_no'], unique=False)
    op.create_index(op.f('ix_job_master_overall_status'), 'job_master', ['overall_status'], unique=False)
    op.create_index(op.f('ix_job_master_sap_customer_code'), 'job_master', ['sap_customer_code'], unique=False)
    op.create_index(op.f('ix_job_master_sap_job_card_doc_entry'), 'job_master', ['sap_job_card_doc_entry'], unique=False)
    op.create_table('integration_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('target_system', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Enum('pending', 'success', 'failed', 'retrying', name='integration_state'), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_master.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_event_job_id'), 'integration_event', ['job_id'], unique=False)
    op.create_index(op.f('ix_integration_event_state'), 'integration_event', ['state'], unique=False)
    op.create_table('job_card_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=True),
    sa.Column('paper_type', sa.String(length=100), nullable=True),
    sa.Column('gsm', sa.String(length=20), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('ink_colors', sa.String(length=200), nullable=True),
    sa.Column('quantity_required', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('num_ups', sa.Integer(), nullable=True),
    sa.Column('element_name', sa.String(length=200), nullable=True),
    sa.Column('raw_material_item_code', sa.String(length=50), nullable=True),
    sa.Column('paper_brand', sa.String(length=200), nullable=True),
    sa.Column('total_sheets', sa.Float(), nullable=True),
    sa.Column('paper_supplied_by', sa.String(length=50), nullable=True),
    sa.Column('wastage_pct', sa.Float(), nullable=True),
    sa.Column('wastage_sheets', sa.Float(), nullable=True),
    sa.Column('print_style', sa.String(length=80), nullable=True),
    sa.Column('mill', sa.String(length=200), nullable=True),
    sa.Column('detail_special_instructions', sa.Text(), nullable=True),
    sa.Column('die_no', sa.String(length=100), nullable=True),
    sa.Column('front_colours', sa.String(length=200), nullable=True),
    sa.Column('back_colours', sa.String(length=200), nullable=True),
    sa.Column('pasting_style', sa.String(length=200), nullable=True),
    sa.Column('print_type_metpet', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_card_printing_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('plate_size', sa.String(length=50), nullable=True),
    sa.Column('number_of_colors', sa.Integer(), nullable=True),
    sa.Column('printing_type', sa.String(length=50), nullable=True),
    sa.Column('finishing_type', sa.String(length=100), nullable=True),
    sa.Column('lamination_type', sa.String(length=50), nullable=True),
    sa.Column('cutting_type', sa.String(length=100), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_card_id')
    )
    op.create_table('job_card_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_detail_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('detail_no', sa.Integer(), nullable=False),
    sa.Column('ups', sa.Integer(), nullable=True),
    sa.Column('element_name', sa.String(length=100), nullable=True),
    sa.Column('raw_material_item_code', sa.String(length=50), nullable=True),
    sa.Column('paper_brand', sa.String(length=100), nullable=True),
    sa.Column('mill', sa.String(length=100), nullable=True),
    sa.Column('total_sheets', sa.Integer(), nullable=True),
    sa.Column('paper_supplied_by', sa.Enum('customer', 'company', name='paper_supplied_by'), nullable=True),
    sa.Column('wastage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wastage_sheets', sa.Integer(), nullable=True),
    sa.Column('sheet_length', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sheet_width', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('print_style', sa.String(length=50), nullable=True),
    sa.Column('print_type', sa.String(length=50), nullable=True),
    sa.Column('front_colours', sa.String(length=100), nullable=True),
    sa.Column('back_colours', sa.String(length=100), nullable=True),
    sa.Column('die_no', sa.String(length=50), nullable=True),
    sa.Column('pasting_style', sa.String(length=50), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_master.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'detail_no', name='uq_job_detail_no')
    )
    op.create_index(op.f('ix_job_detail_line_job_id'), 'job_detail_line', ['job_id'], unique=False)
    op.create_table('job_header_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sap_fg_item_code', sa.String(length=50), nullable=True),
    sa.Column('sap_fg_item_name_snap', sa.String(length=200), nullable=True),
    sa.Column('dispatch_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('ups', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=30), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_master.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'line_no', name='uq_job_line_no')
    )
    op.create_index(op.f('ix_job_header_line_job_id'), 'job_header_line', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_header_line_sap_fg_item_code'), 'job_header_line', ['sap_fg_item_code'], unique=False)
    op.create_table('job_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['job_master.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_status_history_job_id'), 'job_status_history', ['job_id'], unique=False)
    op.create_table('bom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detail_line_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('slip_process_sequence_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detail_line_id'], ['job_detail_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_master.job_no'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detail_line_id', 'version', name='uq_bom_version')
    )
    op.create_index(op.f('ix_bom_detail_line_id'), 'bom', ['detail_line_id'], unique=False)
    op.create_index(op.f('ix_bom_is_active'), 'bom', ['is_active'], unique=False)
    op.create_index(op.f('ix_bom_job_id'), 'bom', ['job_id'], unique=False)
    op.create_table('job_detail_line_fg_involved',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('detail_line_id', sa.Integer(), nullable=False),
    sa.Column('header_line_id', sa.Integer(), nullable=False),
    sa.Column('fg_num', sa.String(length=40), nullable=False),
    sa.Column('sap_so_number', sa.String(length=30), nullable=True),
    sa.Column('sap_so_doc_entry', sa.Integer(), nullable=True),
    sa.Column('sap_so_line_num', sa.Integer(), nullable=True),
    sa.Column('sap_fg_item_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['detail_line_id'], ['job_detail_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['header_line_id'], ['job_header_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_master.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detail_line_id', 'header_line_id', name='uq_job_detail_fg_header')
    )
    op.create_index(op.f('ix_job_detail_line_fg_involved_detail_line_id'), 'job_detail_line_fg_involved', ['detail_line_id'], unique=False)
    op.create_index(op.f('ix_job_detail_line_fg_involved_header_line_id'), 'job_detail_line_fg_involved', ['header_line_id'], unique=False)
    op.create_index(op.f('ix_job_detail_line_fg_involved_job_id'), 'job_detail_line_fg_involved', ['job_id'], unique=False)
    op.create_table('bom_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('process_code', sa.String(length=20), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=20), nullable=True),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('planned_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('output_item_code', sa.String(length=50), nullable=True),
    sa.Column('sap_doc_entry', sa.Integer(), nullable=True),
    sa.Column('sap_doc_num', sa.Integer(), nullable=True),
    sa.Column('sap_warehouse', sa.String(length=20), nullable=True),
    sa.Column('production_order_remarks', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_code'], ['process_master.process_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'seq_no', name='uq_bom_step_seq')
    )
    op.create_index(op.f('ix_bom_step_bom_id'), 'bom_step', ['bom_id'], unique=False)
    op.create_table('bom_step_input',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_step_id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.Enum('raw_material', 'consumable', 'labour', name='bom_input_type'), nullable=False),
    sa.Column('sap_item_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('qty_per_job', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sap_warehouse', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bom_step_id'], ['bom_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_step_input_bom_step_id'), 'bom_step_input', ['bom_step_id'], unique=False)
    op.create_index(op.f('ix_bom_step_input_sap_item_code'), 'bom_step_input', ['sap_item_code'], unique=False)
    _drop_mrp_tables_if_present()
    op.create_index(op.f('ix_generated_fg_items_item_code'), 'generated_fg_items', ['item_code'], unique=False)
    op.drop_constraint(op.f('item_master_item_code_key'), 'item_master', type_='unique')
    op.drop_index(op.f('ix_item_master_item_code'), table_name='item_master')
    op.create_index(op.f('ix_item_master_item_code'), 'item_master', ['item_code'], unique=True)
    op.alter_column('users', 'is_active_user',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active_user',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_item_master_item_code'), table_name='item_master')
    op.create_index(op.f('ix_item_master_item_code'), 'item_master', ['item_code'], unique=False)
    op.create_unique_constraint(op.f('item_master_item_code_key'), 'item_master', ['item_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_generated_fg_items_item_code'), table_name='generated_fg_items')
    op.create_table('mrp_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=False),
    sa.Column('horizon_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mrp_runs_pkey'))
    )
    op.create_table('mrp_recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('recommendation_type', sa.VARCHAR(length=32), server_default=sa.text("'production'::character varying"), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('uom', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('warehouse_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('demand_source', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('on_hand_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('demand_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sap_production_order_entry', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sap_production_order_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['mrp_runs.id'], name=op.f('mrp_recommendations_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mrp_recommendations_pkey'))
    )
    op.create_index(op.f('ix_mrp_recommendations_status'), 'mrp_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_mrp_recommendations_run_id'), 'mrp_recommendations', ['run_id'], unique=False)
    op.drop_index(op.f('ix_bom_step_input_sap_item_code'), table_name='bom_step_input')
    op.drop_index(op.f('ix_bom_step_input_bom_step_id'), table_name='bom_step_input')
    op.drop_table('bom_step_input')
    op.drop_index(op.f('ix_bom_step_bom_id'), table_name='bom_step')
    op.drop_table('bom_step')
    op.drop_index(op.f('ix_job_detail_line_fg_involved_job_id'), table_name='job_detail_line_fg_involved')
    op.drop_index(op.f('ix_job_detail_line_fg_involved_header_line_id'), table_name='job_detail_line_fg_involved')
    op.drop_index(op.f('ix_job_detail_line_fg_involved_detail_line_id'), table_name='job_detail_line_fg_involved')
    op.drop_table('job_detail_line_fg_involved')
    op.drop_index(op.f('ix_bom_job_id'), table_name='bom')
    op.drop_index(op.f('ix_bom_is_active'), table_name='bom')
    op.drop_index(op.f('ix_bom_detail_line_id'), table_name='bom')
    op.drop_table('bom')
    op.drop_index(op.f('ix_job_status_history_job_id'), table_name='job_status_history')
    op.drop_table('job_status_history')
    op.drop_index(op.f('ix_job_header_line_sap_fg_item_code'), table_name='job_header_line')
    op.drop_index(op.f('ix_job_header_line_job_id'), table_name='job_header_line')
    op.drop_table('job_header_line')
    op.drop_index(op.f('ix_job_detail_line_job_id'), table_name='job_detail_line')
    op.drop_table('job_detail_line')
    op.drop_table('job_card_status_history')
    op.drop_table('job_card_printing_specs')
    op.drop_table('job_card_materials')
    op.drop_index(op.f('ix_integration_event_state'), table_name='integration_event')
    op.drop_index(op.f('ix_integration_event_job_id'), table_name='integration_event')
    op.drop_table('integration_event')
    op.drop_index(op.f('ix_job_master_sap_job_card_doc_entry'), table_name='job_master')
    op.drop_index(op.f('ix_job_master_sap_customer_code'), table_name='job_master')
    op.drop_index(op.f('ix_job_master_overall_status'), table_name='job_master')
    op.drop_index(op.f('ix_job_master_original_job_no'), table_name='job_master')
    op.drop_index(op.f('ix_job_master_job_no'), table_name='job_master')
    op.drop_table('job_master')
    op.drop_index(op.f('ix_job_cards_job_card_number'), table_name='job_cards')
    op.drop_table('job_cards')
    op.drop_table('sap_mirror_sync_state')
    op.drop_index(op.f('ix_sap_item_mirror_synced_at'), table_name='sap_item_mirror')
    op.drop_index(op.f('ix_sap_item_mirror_item_type'), table_name='sap_item_mirror')
    op.drop_table('sap_item_mirror')
    op.drop_index(op.f('ix_sap_customer_mirror_synced_at'), table_name='sap_customer_mirror')
    op.drop_table('sap_customer_mirror')
    op.drop_index(op.f('ix_process_master_process_code'), table_name='process_master')
    op.drop_index(op.f('ix_process_master_category'), table_name='process_master')
    op.drop_table('process_master')
    # ### end Alembic commands ###
